import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { getVirtualRange, isIconSetCandidate, normalizeListedIcons, parseStaticIconsetSource, validateIcon } from "../plugins/atlas-plugin/library-core.js";

test("finds icon set JavaScript by filename or icon-named folder under local paths", () => {
  assert.equal(isIconSetCandidate({ path: "/config/www/community/my-icon-pack/icons.js", name: "icons.js", extension: "js", size: 100 }), true);
  assert.equal(isIconSetCandidate({ path: "/config/www/custom-icons/set.js", name: "set.js", extension: "js", size: 100 }), true);
  assert.equal(isIconSetCandidate({ path: "/config/www/community/mdi.js", name: "mdi.js", extension: "js", size: 100 }), false);
  assert.equal(isIconSetCandidate({ path: "/config/www/icon-pack/image.png", name: "image.png", extension: "png", size: 100 }), false);
  assert.equal(isIconSetCandidate({ path: "/config/www/icon-pack/large.js", name: "large.js", extension: "js", size: 64 * 1024 * 1024 + 1 }), false);
});

const sample = { path: "M2 12 12 3l10 9h-3v9h-5v-6h-4v6H5v-9z", viewBox: "0 0 24 24" };

test("validates safe SVG path definitions and defaults the viewBox", () => {
  assert.deepEqual(validateIcon({ path: sample.path }), { path: sample.path, viewBox: "0 0 24 24" });
  assert.throws(() => validateIcon({ path: "M0 0 <script>" }), /SVG path commands/);
});

test("imports the generated static icon set without executing JavaScript", () => {
  const source = `// Generated by ATLAS Icon Studio. Add as a Home Assistant frontend resource.\nwindow.customIconsets = window.customIconsets || {};\nwindow.customIconsets["atlas"] = async (iconName) => {\n  const icons = ${JSON.stringify({ home: sample })};\n  return icons[iconName];\n};\n`;
  assert.deepEqual(parseStaticIconsetSource(source), { prefix: "atlas", icons: [{ name: "home", ...sample }] });
  assert.throws(() => parseStaticIconsetSource(`${source}alert('unsafe')`), /Unsupported icon set/);
});

test("calculates bounded row windows for a large virtualized icon grid", () => {
  assert.deepEqual(getVirtualRange(1000, 9500, 475, 95, 2), { start: 98, end: 107, top: 9310, bottom: 84835 });
  assert.deepEqual(getVirtualRange(3, 0, 600, 95, 2), { start: 0, end: 3, top: 0, bottom: 0 });
});

test("normalizes listable Home Assistant legacy icon sets", () => {
  const icons = normalizeListedIcons("custom", [{ name: "house", keywords: ["home"] }, { name: "bad name" }], (name) => ({ path: name }));
  assert.equal(icons.length, 1);
  assert.equal(icons[0].label, "custom:house");
  assert.deepEqual(icons[0].keywords, ["home"]);
});

test("ships the bundled MDI catalog and license metadata", async () => {
  const catalog = JSON.parse(await readFile(new URL("../plugins/atlas-plugin/mdi-icons.json", import.meta.url), "utf8"));
  assert.equal(catalog.version, "7.4.47");
  assert.ok(catalog.license.includes("Pictogrammers"));
  assert.equal(catalog.icons.length, 7447);
});
