import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { cliIconName, getVirtualRange, isCliSvgCandidate, isIconSetCandidate, normalizeListedIcons, parseStaticIconsetSource, validateIcon } from "../plugins/atlas-plugin/library-core.js";

test("finds icon set JavaScript by filename or icon-named folder under local paths", () => {
  assert.equal(isIconSetCandidate({ path: "/config/www/community/my-icon-pack/icons.js", name: "icons.js", extension: "js", size: 100 }), true);
  assert.equal(isIconSetCandidate({ path: "/config/www/custom-icons/set.js", name: "set.js", extension: "js", size: 100 }), true);
  assert.equal(isIconSetCandidate({ path: "/config/www/community/mdi.js", name: "mdi.js", extension: "js", size: 100 }), false);
  assert.equal(isIconSetCandidate({ path: "/config/www/icon-pack/image.png", name: "image.png", extension: "png", size: 100 }), false);
  assert.equal(isIconSetCandidate({ path: "/config/www/icon-pack/large.js", name: "large.js", extension: "js", size: 64 * 1024 * 1024 + 1 }), false);
});

test("discovers Custom Local Icons SVGs recursively and keeps their relative names", () => {
  const file = { path: "/config/www/custom_local_icons/rooms/kitchen.svg", extension: "svg", size: 300 };
  assert.equal(isCliSvgCandidate(file), true);
  assert.equal(cliIconName(file.path), "rooms/kitchen");
  assert.equal(isCliSvgCandidate({ ...file, path: "/config/www/community/rooms/kitchen.svg" }), false);
  assert.throws(() => cliIconName("/config/www/custom_local_icons/../secret.svg"), /valid/);
});

const sample = { path: "M2 12 12 3l10 9h-3v9h-5v-6h-4v6H5v-9z", viewBox: "0 0 24 24" };

test("validates safe SVG path definitions and defaults the viewBox", () => {
  assert.deepEqual(validateIcon({ path: sample.path }), { path: sample.path, viewBox: "0 0 24 24" });
  assert.throws(() => validateIcon({ path: "M0 0 <script>" }), /SVG path commands/);
});

test("imports the generated static icon set without executing JavaScript", () => {
  const source = `// Generated by ATLAS Icon Studio. Add as a Home Assistant frontend resource.\nwindow.customIconsets = window.customIconsets || {};\nwindow.customIconsets["atlas"] = async (iconName) => {\n  const icons = ${JSON.stringify({ home: sample })};\n  return icons[iconName];\n};\n`;
  assert.deepEqual(parseStaticIconsetSource(source), { prefix: "atlas", icons: [{ name: "home", ...sample }] });
  assert.deepEqual(parseStaticIconsetSource(`${source}alert('unsafe')`).icons, [{ name: "home", ...sample }]);
});

test("imports safe static Home Assistant icon maps used by community sets", () => {
  const thermal = parseStaticIconsetSource(`
    const TC_ICONS_MAP = { "dew-point": { "path": "M 1 1 L 2 2", "keywords": ["dew"] } };
    window.customIcons["tc"] = { getIcon, getIconList };
  `);
  assert.equal(thermal.prefix, "tc");
  assert.deepEqual(thermal.icons[0], { name: "dew-point", path: "M 1 1 L 2 2", viewBox: "0 0 24 24" });

  const knx = parseStaticIconsetSource(`
    const ICONSET_NAME = 'kuf';
    const ICONS = { 'audio_audio': 'M 2 2 L 5 5', };
    window.customIconsets[ICONSET_NAME] = getIcon;
  `);
  assert.equal(knx.prefix, "kuf");
  assert.deepEqual(knx.icons[0], { name: "audio_audio", path: "M 2 2 L 5 5", viewBox: "0 0 24 24" });

  const brand = parseStaticIconsetSource(`
    var icons = { "02tv": [0, 0, 24, 24, "M 3 3 L 6 6"] };
    globalThis.customIconsets.phu = getIcon;
  `);
  assert.equal(brand.prefix, "phu");
  assert.deepEqual(brand.icons[0], { name: "02tv", path: "M 3 3 L 6 6", viewBox: "0 0 24 24" });

  const selfhst = parseStaticIconsetSource(`
    const icons = { "1panel": JSON.parse("[\\\"0\\\",\\\"0\\\",\\\"24\\\",\\\"24\\\",\\\"M 4 4 L 8 8\\\"]"), unusedName, };
    globalThis.customIconsets.selfhst = getIcon;
  `);
  assert.equal(selfhst.prefix, "selfhst");
  assert.equal(selfhst.icons.length, 1);
});

test("rejects executable expressions in community icon maps", () => {
  assert.throws(() => parseStaticIconsetSource(`
    const ICONSET_NAME = "unsafe";
    const ICONS = { test: runCode() };
    window.customIcons["unsafe"] = getIcon;
  `), /Unsupported(?: static)? icon set source/);
});

test("rejects empty icon maps and unrelated scripts even when filenames look like icon sets", () => {
  assert.throws(() => parseStaticIconsetSource(`
    const ICONSET_NAME = "empty";
    const ICONS = { not_an_icon: "", };
    window.customIcons["empty"] = getIcon;
  `), /Unsupported static icon set source/);
  assert.throws(() => parseStaticIconsetSource(`
    const Name = "Custom-icon-color";
    window.customUI = { installEntityCardStylingHook() {} };
  `), /Unsupported(?: static)? icon set source/);
});

test("calculates bounded row windows for a large virtualized icon grid", () => {
  assert.deepEqual(getVirtualRange(1000, 9500, 475, 95, 2), { start: 98, end: 107, top: 9310, bottom: 84835 });
  assert.deepEqual(getVirtualRange(3, 0, 600, 95, 2), { start: 0, end: 3, top: 0, bottom: 0 });
});

test("normalizes listable Home Assistant legacy icon sets", () => {
  const icons = normalizeListedIcons("custom", [{ name: "house", keywords: ["home"] }, { name: "bad name" }], (name) => ({ path: name }));
  assert.equal(icons.length, 1);
  assert.equal(icons[0].label, "custom:house");
  assert.deepEqual(icons[0].keywords, ["home"]);
});

test("ships the bundled MDI catalog and license metadata", async () => {
  const catalog = JSON.parse(await readFile(new URL("../plugins/atlas-plugin/mdi-icons.json", import.meta.url), "utf8"));
  assert.equal(catalog.version, "7.4.47");
  assert.ok(catalog.license.includes("Pictogrammers"));
  assert.equal(catalog.icons.length, 7447);
});
