const ICON_NAME = /^[a-z0-9]+(?:[-_][a-z0-9]+)*$/;
const SVG_PATH = /^[MmZzLlHhVvCcSsQqTtAa0-9.,+\-\sEe]+$/;
const MAX_STATIC_ICON_COUNT = 50000;

export function isIconSetCandidate(file) {
  if (file?.extension !== "js" || !Number.isFinite(file.size) || file.size > 64 * 1024 * 1024) return false;
  const pathParts = String(file.path ?? file.name ?? "").split(/[\\/]+/);
  const directoryParts = pathParts.slice(0, -1);
  return /icon/i.test(file.name ?? "") || directoryParts.some((part) => /icon/i.test(part));
}

export function validateIcon(icon) {
  if (!icon || typeof icon.path !== "string" || !icon.path.trim() || !SVG_PATH.test(icon.path)) {
    throw new TypeError("Icon path must contain SVG path commands only.");
  }
  const viewBox = typeof icon.viewBox === "string" ? icon.viewBox : "0 0 24 24";
  const numbers = viewBox.trim().split(/[\s,]+/).map(Number);
  if (numbers.length !== 4 || numbers.some((value) => !Number.isFinite(value)) || numbers[2] <= 0 || numbers[3] <= 0) {
    throw new TypeError("Icon viewBox must contain four finite values and positive dimensions.");
  }
  return { path: icon.path.trim(), viewBox: numbers.join(" ") };
}

export function parseStaticIconsetSource(source) {
  if (typeof source !== "string" || source.length > 64 * 1024 * 1024) {
    throw new TypeError("Icon set source is missing or too large.");
  }
  const pattern = /^\s*(?:\/\/ Generated by ATLAS Icon Studio\. Add as a Home Assistant frontend resource\.\s*)?window\.customIconsets\s*=\s*window\.customIconsets\s*\|\|\s*\{\s*\};\s*window\.customIconsets\[\s*(["'])([a-z0-9-]+)\1\s*\]\s*=\s*async\s*\(\s*iconName\s*\)\s*=>\s*\{\s*const\s+icons\s*=\s*(\{[\s\S]*?\})\s*;\s*return\s+icons\s*\[\s*iconName\s*\]\s*;\s*\};\s*$/;
  const match = source.match(pattern);
  if (match) {
    const document = JSON.parse(match[3]);
    return normalizeStaticIconMap(match[2], document);
  }

  const prefix = findStaticIconsetPrefix(source);
  if (!prefix) throw new TypeError("Unsupported icon set source.");
  for (const declaration of findStaticIconMapDeclarations(source)) {
    try {
      const document = parseStaticJavaScriptLiteral(source, declaration.valueIndex);
      const icons = normalizeStaticIconMap(prefix, document, findStaticIconsetViewBox(source));
      if (icons.icons.length) return icons;
    } catch {
      // Skip executable or otherwise unsupported declarations without evaluating them.
    }
  }
  throw new TypeError("Unsupported static icon set source.");
}

function normalizeStaticIconMap(prefix, document, fallbackViewBox = "0 0 24 24") {
  if (!/^[a-z0-9-]+$/.test(prefix) || !document || Array.isArray(document) || typeof document !== "object") {
    throw new TypeError("Invalid icon set.");
  }
  const icons = [];
  for (const [name, definition] of Object.entries(document)) {
    if (!ICON_NAME.test(name)) continue;
    let icon;
    if (typeof definition === "string") {
      icon = { path: definition, viewBox: fallbackViewBox };
    } else if (Array.isArray(definition) && definition.length >= 5) {
      icon = {
        path: definition.slice(4).filter(value => typeof value === "string").join(" "),
        viewBox: definition.slice(0, 4).join(" "),
      };
    } else if (definition && typeof definition === "object") {
      icon = {
        path: definition.path,
        viewBox: typeof definition.viewBox === "string" ? definition.viewBox : fallbackViewBox,
      };
    }
    try {
      if (icon) icons.push({ name, ...validateIcon(icon) });
    } catch {
      // Skip definitions that are not plain, valid SVG path data.
    }
    if (icons.length >= MAX_STATIC_ICON_COUNT) break;
  }
  if (!icons.length) throw new TypeError("Icon set is empty or unsupported.");
  return { prefix, icons };
}

function findStaticIconsetPrefix(source) {
  const patterns = [
    /\bICONSET_NAME\s*=\s*(["'])([a-z0-9-]+)\1/,
    /\b(?:customIcons|customIconsets)\s*\[\s*(["'])([a-z0-9-]+)\1\s*\]/,
    /\b(?:customIcons|customIconsets)\.([a-z][a-z0-9-]*)\s*=/,
  ];
  for (const pattern of patterns) {
    const match = source.match(pattern);
    const prefix = match?.[2] ?? match?.[1];
    if (prefix && /^[a-z0-9-]+$/.test(prefix)) return prefix;
  }
  return "";
}

function findStaticIconsetViewBox(source) {
  const match = source.match(/\bviewBox\s*:\s*(["'])([^"']+)\1/);
  return match?.[2] ?? "0 0 24 24";
}

function findStaticIconMapDeclarations(source) {
  const declarations = [];
  const pattern = /\b(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*([{[])/g;
  for (const match of source.matchAll(pattern)) {
    if (!/(?:^icons?$|icon.*(?:map|set)|(?:map|set).*icon)/i.test(match[1])) continue;
    declarations.push({ valueIndex: match.index + match[0].length - 1 });
    if (declarations.length >= 64) break;
  }
  return declarations;
}

function parseStaticJavaScriptLiteral(source, startIndex) {
  let index = startIndex;
  let nodes = 0;
  const skipSpace = () => {
    while (index < source.length) {
      if (/\s/.test(source[index])) { index += 1; continue; }
      if (source.startsWith("//", index)) {
        index = source.indexOf("\n", index + 2);
        if (index < 0) { index = source.length; return; }
        continue;
      }
      if (source.startsWith("/*", index)) {
        const end = source.indexOf("*/", index + 2);
        if (end < 0) throw new TypeError("Unclosed comment in icon set.");
        index = end + 2;
        continue;
      }
      break;
    }
  };
  const parseString = () => {
    const quote = source[index++];
    let value = "";
    while (index < source.length) {
      const character = source[index++];
      if (character === quote) return value;
      if (character !== "\\") { value += character; continue; }
      if (index >= source.length) break;
      const escaped = source[index++];
      const simpleEscapes = { n: "\n", r: "\r", t: "\t", b: "\b", f: "\f", v: "\v", "0": "\0" };
      if (Object.hasOwn(simpleEscapes, escaped)) value += simpleEscapes[escaped];
      else if (escaped === "\n") continue;
      else if (escaped === "\r") { if (source[index] === "\n") index += 1; }
      else if (escaped === "x" || escaped === "u") {
        const digits = escaped === "x" ? 2 : 4;
        const code = source.slice(index, index + digits);
        if (!new RegExp(`^[0-9a-fA-F]{${digits}}$`).test(code)) throw new TypeError("Invalid escape in icon set.");
        value += String.fromCharCode(parseInt(code, 16));
        index += digits;
      } else value += escaped;
    }
    throw new TypeError("Unclosed string in icon set.");
  };
  const parseValue = (depth = 0) => {
    skipSpace();
    nodes += 1;
    if (nodes > 400000 || depth > 32) throw new TypeError("Icon set literal exceeds parsing limits.");
    const character = source[index];
    if (character === "'" || character === '"') return parseString();
    if (source.startsWith("JSON.parse", index)) {
      index += "JSON.parse".length;
      skipSpace();
      if (source[index++] !== "(") throw new TypeError("Invalid static JSON.parse value.");
      skipSpace();
      const json = parseString();
      skipSpace();
      if (source[index++] !== ")") throw new TypeError("Invalid static JSON.parse value.");
      return JSON.parse(json);
    }
    if (character === "{") {
      index += 1;
      const object = Object.create(null);
      skipSpace();
      while (source[index] !== "}") {
        const key = source[index] === "'" || source[index] === '"'
          ? parseString()
          : parseIdentifierOrNumber();
        skipSpace();
        if (source[index] === ":") {
          index += 1;
          object[key] = parseValue(depth + 1);
        } else if (typeof key === "string" && /^[A-Za-z_$][\w$]*$/.test(key)) {
          // Some icon packages append name-only shorthand properties; ignore them safely.
          object[key] = null;
        } else {
          throw new TypeError("Invalid icon set object.");
        }
        skipSpace();
        if (source[index] === "}") break;
        if (source[index++] !== ",") throw new TypeError("Invalid icon set object separator.");
        skipSpace();
      }
      if (source[index++] !== "}") throw new TypeError("Unclosed icon set object.");
      return object;
    }
    if (character === "[") {
      index += 1;
      const array = [];
      skipSpace();
      while (source[index] !== "]") {
        array.push(parseValue(depth + 1));
        skipSpace();
        if (source[index] === "]") break;
        if (source[index++] !== ",") throw new TypeError("Invalid icon set array separator.");
        skipSpace();
      }
      if (source[index++] !== "]") throw new TypeError("Unclosed icon set array.");
      return array;
    }
    const token = parseIdentifierOrNumber();
    if (token === "true") return true;
    if (token === "false") return false;
    if (token === "null") return null;
    if (/^-?(?:\d+\.?\d*|\.\d+)(?:e[+-]?\d+)?$/i.test(token)) return Number(token);
    throw new TypeError("Icon set contains executable expressions.");
  };
  const parseIdentifierOrNumber = () => {
    const match = source.slice(index).match(/^(?:[A-Za-z_$][\w$]*|-?(?:\d+\.?\d*|\.\d+)(?:e[+-]?\d+)?)/i);
    if (!match) throw new TypeError("Invalid icon set token.");
    index += match[0].length;
    return match[0];
  };
  return parseValue();
}

export function getVirtualRange(total, scrollTop, viewportHeight, rowHeight = 96, overscan = 2) {
  const firstVisibleRow = Math.max(0, Math.floor(scrollTop / rowHeight));
  const visibleRows = Math.ceil(viewportHeight / rowHeight);
  const startRow = Math.max(0, firstVisibleRow - overscan);
  const endRow = Math.min(total, firstVisibleRow + visibleRows + overscan);
  return { start: startRow, end: Math.max(startRow, endRow), top: startRow * rowHeight, bottom: Math.max(0, (total - endRow) * rowHeight) };
}

export function normalizeListedIcons(prefix, values, getIcon) {
  if (!Array.isArray(values)) throw new TypeError("Icon list must be an array.");
  const icons = [];
  for (const value of values) {
    const name = typeof value === "string" ? value : value?.name;
    if (typeof name !== "string" || !ICON_NAME.test(name)) continue;
    icons.push({ name, label: `${prefix}:${name}`, keywords: Array.isArray(value?.keywords) ? value.keywords : [], getIcon: () => getIcon(name) });
  }
  return icons;
}
