const ICON_NAME = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const SVG_PATH = /^[MmZzLlHhVvCcSsQqTtAa0-9.,+\-\sEe]+$/;

export function isIconSetCandidate(file) {
  if (file?.extension !== "js" || !Number.isFinite(file.size) || file.size > 64 * 1024 * 1024) return false;
  const pathParts = String(file.path ?? file.name ?? "").split(/[\\/]+/);
  const directoryParts = pathParts.slice(0, -1);
  return /icon/i.test(file.name ?? "") || directoryParts.some((part) => /icon/i.test(part));
}

export function validateIcon(icon) {
  if (!icon || typeof icon.path !== "string" || !icon.path.trim() || !SVG_PATH.test(icon.path)) {
    throw new TypeError("Icon path must contain SVG path commands only.");
  }
  const viewBox = typeof icon.viewBox === "string" ? icon.viewBox : "0 0 24 24";
  const numbers = viewBox.trim().split(/[\s,]+/).map(Number);
  if (numbers.length !== 4 || numbers.some((value) => !Number.isFinite(value)) || numbers[2] <= 0 || numbers[3] <= 0) {
    throw new TypeError("Icon viewBox must contain four finite values and positive dimensions.");
  }
  return { path: icon.path.trim(), viewBox: numbers.join(" ") };
}

export function parseStaticIconsetSource(source) {
  if (typeof source !== "string" || source.length > 64 * 1024 * 1024) {
    throw new TypeError("Icon set source is missing or too large.");
  }
  const pattern = /^\s*(?:\/\/ Generated by ATLAS Icon Studio\. Add as a Home Assistant frontend resource\.\s*)?window\.customIconsets\s*=\s*window\.customIconsets\s*\|\|\s*\{\s*\};\s*window\.customIconsets\[\s*(["'])([a-z0-9-]+)\1\s*\]\s*=\s*async\s*\(\s*iconName\s*\)\s*=>\s*\{\s*const\s+icons\s*=\s*(\{[\s\S]*?\})\s*;\s*return\s+icons\s*\[\s*iconName\s*\]\s*;\s*\};\s*$/;
  const match = source.match(pattern);
  if (!match) throw new TypeError("Unsupported icon set source.");
  const prefix = match[2];
  const document = JSON.parse(match[3]);
  if (!document || Array.isArray(document) || typeof document !== "object") throw new TypeError("Invalid icon set.");
  const icons = Object.entries(document).map(([name, icon]) => {
    if (!ICON_NAME.test(name)) throw new TypeError(`Invalid icon name: ${name}`);
    return { name, ...validateIcon(icon) };
  });
  if (!icons.length) throw new TypeError("Icon set is empty.");
  return { prefix, icons };
}

export function getVirtualRange(total, scrollTop, viewportHeight, rowHeight = 96, overscan = 2) {
  const firstVisibleRow = Math.max(0, Math.floor(scrollTop / rowHeight));
  const visibleRows = Math.ceil(viewportHeight / rowHeight);
  const startRow = Math.max(0, firstVisibleRow - overscan);
  const endRow = Math.min(total, firstVisibleRow + visibleRows + overscan);
  return { start: startRow, end: Math.max(startRow, endRow), top: startRow * rowHeight, bottom: Math.max(0, (total - endRow) * rowHeight) };
}

export function normalizeListedIcons(prefix, values, getIcon) {
  if (!Array.isArray(values)) throw new TypeError("Icon list must be an array.");
  const icons = [];
  for (const value of values) {
    const name = typeof value === "string" ? value : value?.name;
    if (typeof name !== "string" || !ICON_NAME.test(name)) continue;
    icons.push({ name, label: `${prefix}:${name}`, keywords: Array.isArray(value?.keywords) ? value.keywords : [], getIcon: () => getIcon(name) });
  }
  return icons;
}
